/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package WordCounting;

/**
 *
 * @author kresing
 */
public class WordTool extends javax.swing.JFrame {

    /**
     * Creates new form WordTool
     */
    public WordTool() {
        this.setLocationRelativeTo(null); 
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pWordCount = new javax.swing.JPanel();
        lblYourWords = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tATypeWords = new javax.swing.JTextArea();
        btnCountWords = new javax.swing.JButton();
        tFResult = new javax.swing.JTextField();
        lblTotalWords = new javax.swing.JLabel();
        btnClear = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        lblTitle = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pWordCount.setBackground(new java.awt.Color(91, 143, 185));

        lblYourWords.setFont(new java.awt.Font("aakar", 1, 18)); // NOI18N
        lblYourWords.setForeground(new java.awt.Color(182, 234, 218));
        lblYourWords.setText("Type your words");

        tATypeWords.setColumns(20);
        tATypeWords.setRows(5);
        jScrollPane2.setViewportView(tATypeWords);

        btnCountWords.setBackground(new java.awt.Color(48, 30, 103));
        btnCountWords.setFont(new java.awt.Font("aakar", 1, 24)); // NOI18N
        btnCountWords.setForeground(new java.awt.Color(182, 234, 218));
        btnCountWords.setText("Count yours words");
        btnCountWords.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCountWordsActionPerformed(evt);
            }
        });

        tFResult.setFont(new java.awt.Font("aakar", 0, 18)); // NOI18N
        tFResult.setForeground(new java.awt.Color(3, 0, 28));

        lblTotalWords.setFont(new java.awt.Font("aakar", 1, 18)); // NOI18N
        lblTotalWords.setForeground(new java.awt.Color(182, 234, 218));
        lblTotalWords.setText("Total words");

        btnClear.setBackground(new java.awt.Color(48, 30, 103));
        btnClear.setFont(new java.awt.Font("aakar", 1, 14)); // NOI18N
        btnClear.setForeground(new java.awt.Color(182, 234, 218));
        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        btnExit.setBackground(new java.awt.Color(48, 30, 103));
        btnExit.setFont(new java.awt.Font("aakar", 1, 14)); // NOI18N
        btnExit.setForeground(new java.awt.Color(182, 234, 218));
        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        lblTitle.setFont(new java.awt.Font("aakar", 1, 36)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(182, 234, 218));
        lblTitle.setText("Word Count Tool");

        javax.swing.GroupLayout pWordCountLayout = new javax.swing.GroupLayout(pWordCount);
        pWordCount.setLayout(pWordCountLayout);
        pWordCountLayout.setHorizontalGroup(
            pWordCountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pWordCountLayout.createSequentialGroup()
                .addGroup(pWordCountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pWordCountLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(pWordCountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblYourWords)
                            .addComponent(lblTotalWords))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pWordCountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tFResult, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pWordCountLayout.createSequentialGroup()
                        .addGap(188, 188, 188)
                        .addComponent(lblTitle)))
                .addContainerGap(29, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pWordCountLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pWordCountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pWordCountLayout.createSequentialGroup()
                        .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnCountWords, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(90, 90, 90))
        );
        pWordCountLayout.setVerticalGroup(
            pWordCountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pWordCountLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle)
                .addGap(13, 13, 13)
                .addGroup(pWordCountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblYourWords, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnCountWords, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pWordCountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTotalWords)
                    .addComponent(tFResult, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pWordCountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(9, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pWordCount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pWordCount, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
      System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        tATypeWords.setText("");
        tFResult.setText("");
        
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnCountWordsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCountWordsActionPerformed
        String sentence = tATypeWords.getText();
        
        tFResult.setText(Integer.toString(sentence.trim().length()));
    }//GEN-LAST:event_btnCountWordsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WordTool.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WordTool.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WordTool.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WordTool.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WordTool().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnCountWords;
    private javax.swing.JButton btnExit;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTotalWords;
    private javax.swing.JLabel lblYourWords;
    private javax.swing.JPanel pWordCount;
    private javax.swing.JTextArea tATypeWords;
    private javax.swing.JTextField tFResult;
    // End of variables declaration//GEN-END:variables
}
